# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b06018dda774fd245fdd4ea910a4b7eb80b3515c4e55c4267017a5a6ccb6f983f663d9a06481b32e7e019b6c5b7c5257b2c9ca18539c648c1f55c711fabeb31e

test:
  secret_key_base: fd4e0a09d96122e8234d4a72d5a70878ccea60d3d24eede662a3e406d6bb6fcce3e88e1899f2906bd8acea95f6c2fe52dd2dbbd396313ea77596ac0f593d84e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
